x-laravel-base: &laravel-base
  build:
    context: .
    dockerfile: Dockerfile.prod
  restart: unless-stopped
  env_file: .env
  environment:
    - APP_ENV=production
    - APP_DEBUG=false
  volumes:
    - ./storage:/var/www/html/storage
    - static-content:/var/www/html/public
  networks:
    - laravel-network
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  # Service 1 : PHP-FPM (application web)
  app:
    <<: *laravel-base
    container_name: stockmanager_app
    command: php-fpm

  # Service 2 : Queue Worker (indépendant)
  worker:
    <<: *laravel-base
    container_name: stockmanager_worker
    command: php artisan queue:work --verbose --tries=3 --timeout=90

  # Service 3 : Scheduler (cron)
  scheduler:
    <<: *laravel-base
    container_name: stockmanager_scheduler
    command: php artisan schedule:work

  # Service 4 : Nginx (web server)
  webserver:
    image: nginx:alpine
    container_name: stockmanager_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-content:/var/www/html/public:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - laravel-network
    depends_on:
      - app

  # Service 5 : PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: stockmanager_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      # PORT
      POSTGRES_PORT: ${DB_PORT:-5432}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE:-postgres} -U ${DB_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Service 6 : Redis
  redis:
    image: redis:7-alpine
    container_name: stockmanager_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  laravel-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  static-content:
