version: '3.8'

services:
  app:
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true

  webserver:
    volumes:
      - ./docker/nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf

  db:
    ports:
      - "5433:5432"  # Différent port pour éviter conflit avec Laragon
